config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/home',    to: 'static_pages#home'
  get  '/contact', to: 'static_pages#contact'
  get '/todos', to: 'static_pages#todos'
  get '/register',   to: 'users#new'
  post '/register',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # put '/todone', to: 'todos#todone'

  resources :users
  resources :todos, only: [:create, :update, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord

  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true

  def change_status
    update_attribute(:content, nil)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos, dependent: :destroy

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # forget a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def feed
    Todo.where(user_id: id).where(completed: nil)
  end

  def full_feed
    Todo.where(user_id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash.now[:success] = "You are successfully logged in!"
      log_in user
      remember user
      redirect_to root_url
    else
      flash.now[:danger] = "Invalid email/password combination!"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @todo = current_user.todos.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def todos
    @todo = current_user.todos.build
    @full_feed_items = current_user.full_feed.paginate(page: params[:page])
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :logged_in_user, only: [:update, :destroy, :create]

  def create
    @todo = current_user.todos.build(todo_params)
    if @todo.save
      flash[:success] = "Todo created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end


  def update
    @todo = Todo.find(params[:id])
    @todo.update_attribute(:completed, "true")
    redirect_to root_url
  end

  def todone
    @todo.update_attribute(:content, nil)
  end



  private

    def todo_params
      params.require(:todo).permit(:content)
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update]
  before_action :correct_user, only: [ :edit, :update]

  def show
    @user = User.find(params[:id])
    @todos = @user.todos.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
    #if logged_in?
    #  flash[:success] = "logged in"
    #end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "thanks for signing up!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    #creates session with the user.id stored as user_id
    session[:user_id] = user.id
  end

  def remember(user)
    #calls remember in user.rb
    user.remember
    #sets cookies for userid & remember token
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  # returns current logged-in user
  def current_user
    #checks to see if @current_user is set. if it isn't, find it via session[:user_id]
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    # calls forget in user.rb
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
  <small>
    &copy; SRCurran, 2018
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",   help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css?family=Roboto+Mono|Roboto:400,700" rel="stylesheet">

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <%= link_to "Jobber", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Clients", '#' %></li>
          <li><%= link_to "Jobs", '#' %></li>
          <li><%= link_to "Todos", todos_path %></li>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <span class="caret"></span>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span>
            <ul class="dropdown-menu">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Log in", login_path %></li>
              <li><%= link_to "Register", register_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> - Jobberuby</title>
    <%=render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <main class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_current_user.html.erb
<%= link_to current_user.name, current_user %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="todos">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_full_feed.html.erb
<% if @full_feed_items.any? %>
  <ol class="todos">
    <%= render @full_feed_items %>
  </ol>
  <%= will_paginate @full_feed_items %>
<% end %>

app/views/shared/_todo_form.html.erb
<%= form_for(@todo) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new todo..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact Us</h1>
<p>If you're having any issues, reach out to me on twitter <a target="_blank" href="https://twitter.com/srcurran">@srcurran</a></p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Home</h1>
<% if logged_in? %>
  <div class="row">
    <div class="col-md-8">
      <section class="user_info">
        Hello, <%= render 'shared/current_user' %>
      </section>
    </div>
    <div class="col-md-8">
      <h3>Todo List</h3>
      <%= render 'shared/feed' %>
      <section class="todo_form">
        <%= render 'shared/todo_form' %>
      </section>
    </div>
  </div>



<% else %>
  <p>Find me in app/views/static_pages/home.html.erb</p>
  <p><%= link_to "Register", register_path %> </p>
  <p><%= link_to "Log in", login_path %> </p>
<% end %>

app/views/static_pages/show.html.erb
<div class="col-md-8">
<h1>User Information</h1>
<%= render @user %>
</div>

<div class="col-md-8">
  <% if @user.todos.any? %>
    <h3>Todos</h3>
    <ol class="todos">
      <%= render @todos %>
    </ol>
    <%= will_paginate @todos %>
  <% end %>
</div>

app/views/static_pages/todos.html.erb
<h1>Todos</h1>
<% if logged_in? %>
  <div class="row">
    <div class="col-md-8">
      <h3>Todo List</h3>
      <%= render 'shared/full_feed' %>
    </div>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<li>
  <div class="content"><%= todo.content %></div>
  <div class="meta">Status = <%= todo.completed %></div>
  <span class="meta">Posted <span class="author">by <%= link_to todo.user.name, todo.user %></span> <span class="timestamp"><%= time_ago_in_words(todo.created_at) %> ago.</span>
  <div><%= link_to "Completed", todo, method: :put %>
</li>

app/views/users/_user.html.erb
<%= link_to user.name, user %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users Information</h1>
<p>here are all the users</p>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= render user %>
    </li>
  <% end %>
  <%= will_paginate %>
</ul>

app/views/users/new.html.erb
<h1>Register</h1>
<p>Find me in app/views/users/new.html.erb</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: register_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>
  <a href="signin">Sign In</a>
  <a href="register">Register</a>
</p>